workout_app/models.py
from workout_app import db
from sqlalchemy_utils import URLType
from flask_login import UserMixin

class Exercise(db.Model):
    """Exercise Model"""
    #Import data from Exercise Form as to which category & body part worked
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)
    bodyPart = db.Column(db.String(80), nullable=False)
    category = db.Column(db.String(80), nullable=False)
    routines = db.relationship('Routine', secondary='routine_exercise', back_populates='exercises')


    def __repr__(self):
        return self.name
    #If I want pounds and reps to be contingent on the type of category, make nullable set to true.
    #I want to hide certain form fields (FrontEnd work)
    #If i want to reject information on back end i could use a validator to reject form based on category.

routine_exercise = db.Table('routine_exercise',
    db.Column('exercise_id', db.Integer, db.ForeignKey('exercise.id')),
    db.Column('routine_id', db.Integer, db.ForeignKey('routine.id'))
)


class Routine(db.Model):
    """Routine Model"""
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)
    exercises = db.relationship('Exercise', secondary='routine_exercise', back_populates='routines')


    def __repr__(self):
        return self.name
    #How do I set up a many to many exercise routine


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), nullable=False, unique=True)
    password = db.Column(db.String(80), nullable=False)

    def __repr__(self):
        return f'<User: {self.username}>'

workout_app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, DateField, SelectField, SubmitField
from wtforms.ext.sqlalchemy.fields import QuerySelectField, QuerySelectMultipleField
from wtforms.validators import DataRequired, Length, URL
from workout_app import db
from workout_app.models import Exercise, Routine


class ExerciseForm(FlaskForm):
    """Form for adding a new exercise"""
    #Exercise name
    name = StringField('Name', validators=[DataRequired()])
    #Body part worked
    bodyPart = SelectField('Body Part', choices=[('Core','Core'),('Arms','Arms'),('Back','Back'),('Chest','Chest'),('Legs','Legs'),('Shoulders','Shoulders'),('Other','Other'),('Olympic','Olypmic'),('Full Body','Full Body'),('Cardio','Cardio')])
    #Type of exercise
    category = SelectField('Category', choices=[('Barbell','Barbell'),('Dumbbell','Dumbell'),('Machine/Other','Machine/Other'),('Weighted Bodyweight','Weighted Bodyweight'),('Assisted Bodyweight','Assisted Bodyweight'),('Reps Only','Reps Only'),('Cardio','Cardio'),('Duration','Duration')])
    submit = SubmitField('Submit')

#Access the data held within Exercise form import it
#Make sure form labels match models

class RoutineForm(FlaskForm):
    """Form for adding a new routine"""
    #Routine Name
    name = StringField('Name', validators=[DataRequired()])
    #TODO: I want the choices to be a list of the pre-existing workouts already stored in the datavse.
    exercises = QuerySelectMultipleField('Exercise',
        query_factory=lambda: Exercise.query)
    submit = SubmitField('Submit')
    #List of Exercises One to Many or Many to Many
    #Book & Genre exercise will help!

workout_app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bcrypt import Bcrypt
from workout_app.config import Config
import os

app = Flask(__name__)
app.config.from_object(Config)
app.secret_key = os.urandom(24)

db = SQLAlchemy(app)

#########################
#   Authentication
#########################

login_manager = LoginManager()
login_manager.login_view = 'auth.login'
login_manager.init_app(app)

from .models import User

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

bcrypt = Bcrypt(app)

##########################
#   Blueprints
##########################

from workout_app.main.routes import main as main_routes
app.register_blueprint(main_routes)

from workout_app.auth.routes import auth as auth_routes
app.register_blueprint(auth_routes)

with app.app_context():
    db.create_all()

workout_app/main/routes.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required, current_user
from workout_app.models import Exercise, Routine
from workout_app.forms import ExerciseForm, RoutineForm
from workout_app import bcrypt

from workout_app import app, db

main = Blueprint("main", __name__)

##########################################
#               Routes                  #
#########################################

@main.route('/')
def homepage():
    #TODO: Create homepage
    return render_template('homepage.html')

@main.route('/add_exercise', methods=['GET', 'POST'])
@login_required
def add_exercise():
    form = ExerciseForm()

    if form.validate_on_submit():
        new_exercise = Exercise(
        name=form.name.data,
        bodyPart=form.bodyPart.data,
        category=form.category.data
        )
        db.session.add(new_exercise)
        db.session.commit()

        flash('Exercise created successfully')
    return render_template('add_exercise.html', form=form)



@main.route('/create_routine', methods=['GET', 'POST'])
@login_required
def create_routine():
    form = RoutineForm()
    
    if form.validate_on_submit():
        new_routine = Routine(
            name=form.name.data,
            exercises=form.exercises.data
        )
        db.session.add(new_routine)
        db.session.commit()

        flash('Routine created successfully')
    return render_template('create_routine.html', form=form)

workout_app/templates/add_exercise.html
{% extends 'homepage.html' %}

{% block content %}

<form method="POST" action="{{ url_for('main.add_exercise') }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Create an exercise</legend>

        {{ form.name.label }}
        {{ form.name }}
        <ul>
        {% for error in form.name.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>
        {{ form.bodyPart.label }}
        {{ form.bodyPart }}
        <ul>
        {% for error in form.bodyPart.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>
        {{ form.category.label }}
        {{ form.category }}
        
        <!--Show a submit button!-->
        
        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

workout_app/templates/create_routine.html
{% extends 'homepage.html' %}

{% block content %}

<form method="POST" action="{{ url_for('main.create_routine') }}">
    {{ form.csrf_token}}
    <fieldset>
        <legend>Create a Routine</legend>

        {{ form.name.label }}
        {{ form.name }}
        <ul>
            {% for error in form.name.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
            </ul>
            {{ form.exercises.label }}
            {{ form.exercises }}
            <ul>
            {% for error in form.exercises.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
            </ul>
            <!--Show a submit button!-->
            
            {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

workout_app/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Workout App</title>
</head>
<body>
    <nav>
        <a href="/">Home</a>
        <div>
            {% if current_user.is_authenticated %}
            <a href="/add_exercise">Add New Exercise</a>
            <a href="/create_routine">Create Routine</a>
            <a href="/logout">Log Out</a>
            {% else %}
            <a href="/login">Login</a>
            <a href="/signup">Sign Up</a>
            {% endif %}
        </div>
    </nav>
    
    {% if current_user.is_authenticated %}
    <p>You are logged in as {{ current_user.username }}</p>
    {% endif %}

    {% for message in get_flashed_messages() %}
        <p>{{ message }}</p>
    {% endfor %}

    {% block content %}{% endblock %}
</body>
</html>

workout_app/templates/login.html
{% block content %}

<h1>Log In</h1>

<form action="/login" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter your credentials</legend>

        {{ form.username.label }}
        {{ form.username }}
        <ul>
        {% for error in form.username.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
        {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

workout_app/templates/signup.html
{% block content %}

<h1>Sign Up</h1>

<form action="/signup" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter your credentials</legend>

        {{ form.username.label }}
        {{ form.username }}
        <ul>
        {% for error in form.username.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
        {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.submit }}

    </fieldset>
</form>

{% endblock %}